Format update
mdolab/idwarp pull request #35
Opened 2020-10-31 10:03 UTC by marcomangano

## Purpose
I re-formatted the code, as per [this issue](https://github.com/mdolab/private-docs/issues/191).
The first two commits are the `black` and manual `flake8` fixes respectively.
I committed separately a few fixes that I would like the reviewers to double check carefully, to be sure that the code behaviour is not changing

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Checklist

- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

2020-10-31 15:03 UTC, nwu63 commented on src/complexify.py
> +from stat import *  # noqa: F403
Could you not tell what the star imports were?

2020-10-31 15:03 UTC, nwu63 commented on reg_tests/mdo_regression_helper.py
> +    print("This comp should be True: ", _reg_str_comp(str1, str2))
I forget, why is this change necessary?

2020-10-31 15:05 UTC, nwu63 commented on idwarp/MultiUnstructuredMesh.py
>      from cgnsutilities import cgns_utils as cs
This actually reminds me, we changed the file names, so this should probably be updated to
`from cgnsutilities import cgnsutilities as cs`

2020-10-31 15:05 UTC, nwu63 commented on src/complexify.py
> +from stat import *  # noqa: F403
Never mind I see you fixed this later on.

2020-10-31 15:06 UTC, nwu63 commented on src/complexify.py
> -        f.close()
I suspect this was supposed to be `g.close()` I think? Not really sure.

2020-10-31 15:08 UTC, nwu63 commented
So I am a tiny bit uneasy about fixing `complexify.py` just because it's so old it needs a total overhaul. What I would recommend is reverting those files to how they were, and if you add a `.flake8` file just to ignore those files, then Travis will work its magic. We can fix these at a later date.

See for example [this file](https://github.com/mdolab/pyoptsparse/blob/master/.flake8).

2020-10-31 15:15 UTC, marcomangano commented on reg_tests/mdo_regression_helper.py
> +    print("This comp should be True: ", _reg_str_comp(str1, str2))
`reg_comp` does not exist anymore - I believed you renamed it to `_reg_str_comp`, but this was not caught as an error because we never run `python mdo_regression_helper.py`

2020-10-31 15:17 UTC, marcomangano commented on src/complexify.py
> -        f.close()
Yes, that was my guess too... but then I realized that it did not make sense to close something that was never opened, so I removed it altogether. I can put `g.close()` back in, but one way or the other that except is going to exit the run - more or less gracefully

2020-10-31 15:18 UTC, marcomangano commented
> So I am a tiny bit uneasy about fixing `complexify.py` just because it's so old it needs a total overhaul. What I would recommend is reverting those files to how they were, and if you add a `.flake8` file just to ignore those files, then Travis will work its magic. We can fix these at a later date.
> 
> See for example [this file](https://github.com/mdolab/pyoptsparse/blob/master/.flake8).

Yeah, I was a bit uneasy too but I gave it a shot. I will revert it back as you suggest

2020-10-31 15:25 UTC, marcomangano commented
I will fix `complexify` by the end of the day

2020-10-31 15:26 UTC, nwu63 commented
Sure, instead of reverting commits you can just copy/paste what we had before and do a single commit that way.

2020-10-31 15:33 UTC, marcomangano commented
> Sure, instead of reverting commits you can just copy/paste what we had before and do a single commit that way.

That's the only way I am able to do it ahaha

2020-10-31 15:45 UTC, marcomangano commented
@nwu63 this should fix it?

2020-10-31 15:47 UTC, nwu63 commented
Good except you still need to run `black` on it

2020-10-31 16:18 UTC, nwu63 approved these changes
Good with me but I'd prefer someone else to also take a look.

2020-11-02 11:38 UTC, eirikurj requested changes
Few minor things, otherwise looks good.

2020-11-02 11:38 UTC, eirikurj commented on idwarp/MultiUnstructuredMesh.py
> +            self.warp = MExt("idwarp", [curDir])._module
To maintain consistency please keep this argument and add a default value `debug=False` in the `__init__` function.

2020-11-02 11:38 UTC, eirikurj commented on idwarp/MultiUnstructuredMesh.py
> +        self.myID = self.comm.Get_rank()
Instead of overwriting the value (which is set once in the `__init__` function) please just remove this line (and the ones below).

2020-11-02 11:38 UTC, eirikurj commented on idwarp/MultiUnstructuredMesh.py
> +                print(" Options of mesh", mesh, "of", len(self.meshes))
This will print out the handle to the mesh object. Not sure this is the desired behavior.

2020-11-02 11:38 UTC, eirikurj requested changes
Few minor things, otherwise looks good.

2020-11-02 11:51 UTC, marcomangano commented
> Few minor things, otherwise looks good. Do we want to add the black/flake8 commit to a git blame ignore file?

@nwu63 what is our final position on this? I have one I can add now, but we realized that such file is only useful locally.. other ppl must initialize it in their git option for it to work, and still it is not effective on the browser interface. Your call guys!

2020-11-02 12:03 UTC, eirikurj approved these changes

2020-11-02 14:42 UTC, nwu63 commented
Yeah personally I don't see much value in it since git cannot pick it out automatically, and it just sort of clutters the repo. Most tools can `git blame` multiple times and as long as your commit message is clear I think it's fine.

2020-11-02 22:05 UTC, nwu63 approved these changes

2020-11-02 22:13 UTC, merged