Options refactoring and docs update
mdolab/idwarp pull request #38
Opened 2021-01-06 21:11 UTC by sseraj

## Purpose

This PR refactors the code to:
1) Automatically generate the options documentation
2) Make the USMesh class inherit from BaseSolver in baseclasses

The option type and value checking in BaseSolver breaks backward compatibility for some run scripts. This is usually only an issue for `fileType` because string-type values are now case sensitive. The actually functionality is unchanged. 

I checked that these changes will not break the tests in ADflow or DAFoam. The tutorial run scripts should be fine as well. However, the pyAeroStructure tests will break. @eirikurj will fix the options either for the current tests or with the [testflo update](https://github.com/mdolab/pyaerostructure/pull/32).

Once this is merged, the maintainers should make a new release and make these incompatibilities clear in the release notes. [Here is an example](https://github.com/mdolab/pyhyp/releases/tag/v2.3.0).

One note for those more familiar with the code: PLOT3D mesh format looks like it is supported, but this is not mentioned anywhere in the options docs and is not tested. I have excluded ``plot3d`` from the ``fileType`` option for now. Let me know if I should add it.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [x] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
See the [BaseSolver tests](https://github.com/mdolab/baseclasses/blob/master/tests/test_BaseSolver.py) for examples on how the type and value checking works.

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

2021-01-07 22:33 UTC, joanibal submitted a review, later dismissed

2021-01-11 16:17 UTC, eirikurj requested changes

2021-01-11 16:17 UTC, eirikurj commented on idwarp/UnstructuredMesh.py
> +                Warning(
I think we should cast an `raise Error` here instead. I would rather like to know immediately that the option supplied had no effect than finding it out later.

2021-01-11 19:35 UTC, sseraj commented on doc/options.yaml
> +fileType:
I added `plot3d` to the list. The documentation still focuses on CGNS and OpenFOAM though, so let me know if there is `plot3d` related information to add to the other descriptions (for example, how to set symmetry planes).

2021-01-15 16:48 UTC, nwu63 commented on idwarp/UnstructuredMesh.py
> +        if self.getOption("aExp") != 3.0 or self.getOption("bExp") != 5.0:
Shouldn't we just _not_ have these as possible options...?

2021-01-17 00:23 UTC, sseraj commented on idwarp/UnstructuredMesh.py
> +        if self.getOption("aExp") != 3.0 or self.getOption("bExp") != 5.0:
If having these as options could be useful, we should see if someone can finish the implementation. If no one will work on it, then we should remove them. What do think @eirikurj?

2021-01-17 00:37 UTC, sseraj commented
After further discussion, we have decided to change the capitalization of the accepted `fileType` strings. This will break the current ADflow and DAFoam tests. I have updated the PR description accordingly. Tagging @friedenhe so you are aware.

2021-01-19 11:47 UTC, eirikurj commented on idwarp/UnstructuredMesh.py
> +        if self.getOption("aExp") != 3.0 or self.getOption("bExp") != 5.0:
Right it is kind of strange to have "options" that are not actually options.
To make these into proper options does require some changes, but overall is not difficult. There will be some penalty in terms of performance, but if we think this is useful, and want the flexibility, then I think we should change the code to include them.
Let me know what you think and if we want these in I could update the code. This would probably be a separate PR though, or would it make sense to include this here?

2021-01-19 15:12 UTC, nwu63 commented on idwarp/UnstructuredMesh.py
> +        if self.getOption("aExp") != 3.0 or self.getOption("bExp") != 5.0:
I don't really know what these options are supposed to control, so I can't say whether they'd be useful. But if we want to implement these, that should probably be a separate PR, and these can stay in for now.

2021-01-19 18:57 UTC, sseraj commented on idwarp/UnstructuredMesh.py
> +        if self.getOption("aExp") != 3.0 or self.getOption("bExp") != 5.0:
I opened issue #40 for this. Let's keep the options for now and finish the implementation in another PR.

2021-01-19 21:55 UTC, nwu63 approved these changes
I think this one is ready right @eirikurj?

2021-01-19 21:57 UTC, eirikurj approved these changes

2021-01-19 21:58 UTC, merged