Azure transition
mdolab/idwarp pull request #46
Opened 2021-02-12 01:40 UTC by bernardopacini

## Purpose
This PR adds Azure pipelines testing to replace travis. The Azure yaml and build bash scripts are included in the `.github` directory.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [X] Maintenance update
- [ ] Other (please describe)

## Testing
Azure has successfully run the build and test stages.

## Checklist
_Put an `x` in the boxes that apply._

- [ ] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

2021-02-12 01:59 UTC, bernardopacini commented
- [ ] Add Azure pipelines badge to readme

2021-02-12 02:44 UTC, nwu63 requested changes

2021-02-12 02:44 UTC, nwu63 commented on .github/build_complex.sh
> +make
Complex build does not need the `make` step since that builds the real version

2021-02-12 02:55 UTC, sseraj commented on .github/build_complex.sh
> +make
The way the IDWarp tests are right now does really work with separate complex and real tests. If only the real build is present, the complex tests are skipped, but not the other way around. As a result, the complex tests are actually duplicating the real tests right now.
 
We can keep this as is, or I can change the tests to skip the real tests if only complex is built.

2021-02-12 04:19 UTC, nwu63 commented on .github/build_complex.sh
> +make
Oh I see. I personally don't see a lot of value in splitting up IDwarp into real/complex since the whole thing is fast. For the lowest-effort approach, we can just set `COMPLEX` to false, and throw everything into the "real" build. Would that be okay? If we are having separate complex builds, then I think we should fix this to properly split the tests up.

2021-02-12 04:28 UTC, sseraj commented on .github/build_complex.sh
> +make
Would skipping the real tests if only complex is built be good enough? This should be a pretty easy change.

2021-02-12 04:30 UTC, nwu63 commented on .github/build_complex.sh
> +make
Yeah, that's how ADflow tests are done. Real tests use the default `test_*` glob, while complex tests are triggered with `complex_test*` or similar. No need for `skipTest` or something like that to skip the tests.

2021-02-12 04:34 UTC, sseraj commented on .github/build_complex.sh
> +make
Here the exact same tests are run with real and complex using `parameterized` so I was leaning towards the `skipTest` approach.

2021-02-12 04:39 UTC, nwu63 commented on .github/build_complex.sh
> +make
Ah okay, that works fine too.

2021-02-13 15:30 UTC, nwu63 approved these changes

2021-02-15 18:08 UTC, sseraj approved these changes

2021-02-15 19:52 UTC, merged