Renamed compiled library to `libidwarp`
mdolab/idwarp pull request #50
Opened 2021-05-01 01:49 UTC by nwu63

## Purpose
Addresses #24.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Testing
Build/tests work locally for both real and complex.

## Checklist
_Put an `x` in the boxes that apply._

- [ ] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

2021-05-01 14:00 UTC, eirikurj requested changes

2021-05-01 14:00 UTC, eirikurj commented on .gitignore
> +src_cs/f2py/idwarp_cs-f2pywrappers.f90
Naming here is inconsistent with the actual filename, should be `libidwarp`

2021-05-01 14:00 UTC, eirikurj commented on .gitignore
> +src/f2py/idwarp.pyf.autogen
I would actually also rename the pyf file to `libidwarp` since the pyf file is for the module.

2021-05-01 14:01 UTC, nwu63 commented on .gitignore
> +src_cs/f2py/idwarp_cs-f2pywrappers.f90
Whoops good catch

2021-05-01 14:01 UTC, nwu63 commented on .gitignore
> +src/f2py/idwarp.pyf.autogen
Right that makes sense. I didn't do it since adflow didn't do it but I'll make the changes here

2021-05-02 10:08 UTC, eirikurj approved these changes

2021-05-03 13:39 UTC, Xiaosong2105 approved these changes

2021-05-03 13:51 UTC, merged